### PR TITLE
Fix shared library build on Cygwin

### PR DESCRIPTION
**Pull request by mkoeppe**
See https://trac.sagemath.org/ticket/29152

### CODE REVIEW

**Comment by simon-king-jena** [comment]
Hi Matthias,

I know that it took a long time since my last contribution to
SharedMeatAxe. But as much as I see, there is stuff in the develop
branch that should probably be part of the next release. So, I wonder if
there is a merge conflict of your pull request with the new stuff in the
develop branch.

Since I am not so often working with github, can you please tell me if
the following is the way to proceed: I click on your pull request (I
suppose this would add your commits to the remote master branch), then I
go to my local master branch, pull the remote branch into my local
branch, try to merge my develop branch, and push? And do some tests at
some point?

Best regards,
Simon

Am 13.09.20 um 01:50 schrieb Matthias Köppe:

**Comment by simon-king-jena** [comment]
I have a question on your pull request: The SharedMeatAxe can build its documentation - I took this from the original ("unshared") MeatAxe. So, can you please explain what the doxygen file does?

**Comment by mkoeppe** [comment]
> The SharedMeatAxe can build its documentation - I took this from the original ("unshared") MeatAxe. So, can you please explain what the doxygen file does?

The added file supplies the definitions of the doxygen-related macros used in `configure.ac`. It is possible that these macros are installed systemwide on some systems, but they are not installed for example by the homebrew package for doxygen on macOS. I added them in the `m4` folder, which is part of the best practices for distributing packages that use autotools.

**Comment by mkoeppe** [comment]
Hi Simon,
> But as much as I see, there is stuff in the develop branch that should probably be part of the next release. So, I wonder if there is a merge conflict of your pull request with the new stuff in the develop branch. Since I am not so often working with github, can you please tell me if the following is the way to proceed: I click on your pull request (I suppose this would add your commits to the remote master branch), then I go to my local master branch, pull the remote branch into my local branch, 

Yes, exactly, up to this point. 
At this point, it would be helpful if you could make a new release tarball using `make distcheck` so that we can use it on the Sage ticket.

Then either do what you described:
> try to merge my develop branch, and push? And do some tests at some point? 
Or check out the develop branch, merge the updated master into it, get develop running and tested, and finally merge develop into master.

**Review by simon-king-jena — APPROVED** [review]
The added doxygen file apparently is missing on some systems and thus needs to be supplied

**Review by simon-king-jena — APPROVED** [review]
.gitignore should of course be added.

**Review by simon-king-jena — APPROVED** [review]
There will be a merge conflict with the develop branch, as it bumps the version number, too (will be 1.1), but that shouldn't be much of a problem.

**Comment by simon-king-jena** [comment]
Hi Matthias,

just to keep you updated: Strange things happened.

First, I merged your pull requests into master, pulled it to my local
repository, and rebased my develop branch on top of the new master. Then
I did tests, and everything passed.

Then, I remembered that "rebasing" means I'd have to force-push, so, I
went back to the old develop branch, and merged the master, instead of
rebasing.

Do I understand correctly that both should result in exactly the same
code, only the git history would differ? Then I don't understand why
suddenly 11 of the tests fail. Very strange. Is there an easy explanation?

Best regards,
Simon


Am 13.09.20 um 18:06 schrieb Matthias Köppe:

**Comment by simon-king-jena** [comment]
... and it becomes even stranger (to me at least).

My local repository is in ~/Projekte/MeatAxe/autoconfiscate, I build and
test in ~/Projekte/MeatAxe/build.

Being in the build/ directory, I do

    ../autoconfiscate/configure --prefix=/home/king/Projekte/MeatAxe/build/

It used to work just fine. But now, regardless whether I am on the
develop branch or the master branch (which are both identical with the
corresponding remote branches), I get

    ../autoconfiscate/configure: line 12369: syntax error near
unexpected token `ON'
    ../autoconfiscate/configure: line 12369: `DX_DOXYGEN_FEATURE(ON)'

What the heck is going on? I reckon that the previous successful build
(when I rebased develop on top of master instead of merging master into
develop) only worked since at that point the build/ directory wasn't
empty. But now I emptied build/ before running "configure".

Best regards,
Simon

Am 13.09.20 um 18:06 schrieb Matthias Köppe:

**Comment by simon-king-jena** [comment]
Aha! I did autoreconf before, but perhaps some time stamps were wrong. After "autoreconf -f -i", configure works.

**Comment by simon-king-jena** [comment]
Fortunately the strangeness has disappeared: All tests pass on master, 11 tests fail on develop, regardless whether develop merges master or is rebased on top of master.

My plan: Fix the tests (or rather the underlying issues) and also fix the compiler warnings that I get on develop.

**Comment by mkoeppe** [comment]
Glad this worked out! 

If you could make a quick 1.0.1 release from the master branch, that would be very helpful for moving https://trac.sagemath.org/ticket/29152 forward. Just `git tag -a -m "Version 1.0.1" v1.0.1 && git push origin v1.0.1 && ./configure && make distcheck` and then upload the release tarball to https://github.com/simon-king-jena/SharedMeatAxe/releases

**Pull request merged**
